### ISSUE TITLE
Need help.

### ISSUE THREAD

**Issue by aakashgangolli3112** [shineyruan/F1Tenth_Labs#1]
Hi. I am starting with f1tenth and referring to your lab submissions. What should happen when I do "rosrun lab3 wall_follower"? Does the car start wall following on Rviz?

**Comment by shineyruan** [comment]
Yes. You launch f1tenth_simulator in a terminal, and Lab 3 wall_follower in another terminal. Do remember to hit `n` in the f1tenth_simulator console (enable navigation mode). Then the car will start wall following in Rviz.
